#!/bin/bash

DIR = $(pwd)

# Create output Dir
mkdir ${DIR}/output

# Run JAR File
touch ${DIR}/output/index.html; echo "<h1>Hello, world!</h1>" > ${DIR}/output/index.html

# Copy CSS

# Copy JS

# Open in Browser
xdg-open ${DIR}/output/index.html > /dev/null
