#!/bin/bash

DIR=$(pwd)

# Create output Dir
sudo mkdir ${DIR}/output

# Run JAR File
java -jar ${DIR}/ProgressAnalysis.jar $0 $1 $2

# Copy CSS
sudo cp file.css ${DIR}/output
sudo cp index.css ${DIR}/output

# Copy JS
sudo cp index.js ${DIR}/output
sudo cp jquery.js ${DIR}/output

# Open in Browser
sudoxdg-open ${DIR}/output/index.html > /dev/null
